env:
  browser: true
  node: true
  es6: true
extends:
  - airbnb
parser: babel-eslint
parserOptions:
  sourceType: module
  ecmaFeatures:
    jsx: true
plugins:
  - react
settings:
  import/resolver:
    webpack:
      config: ./webpack.dev.js
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  react/jsx-filename-extension:
    - 1
    - extensions:
      - ".js"
      - ".jsx"
  valid-jsdoc:
    - error
  require-jsdoc:
    - error
    -
      require:
        FunctionDeclaration: true
        MethodDefinition: true
        ClassDeclaration: true
globals:
  it: true
  should: true
  jest: true
  describe: true
  expect: true
